config/routes.rb
Rottenpotatoes::Application.routes.draw do

  resources :movies

  get 'movies/:id/director' => 'movies#director', as:'director'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date, :director

  def Movie.all_ratings
  	['G', 'PG', 'PG-13', 'R']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
require 'debugger'
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @all_ratings = Movie.all_ratings
    sort = params[:sort]
    ratings = params[:ratings]
    sort_not_change = false
    ratings_not_change = false
    if ratings
      @existing = ratings
      session['ratfil'] = @existing
    elsif session['ratfil']
      @existing = session['ratfil']
      ratings_not_change = true
    else
      @existing = {"G" =>"1", "PG" =>"1","PG-13" =>"1", "R" =>"1"}
      session['ratfil'] = @existing
    end
    @movies = Movie.where(rating: @existing.keys)

    if sort
      if sort == 'title'
        @movies = @movies.order(:title)
        session['sortfil'] = 'title'
      else
        @movies = @movies.order(:release_date)
        session['sortfil'] = 'date'
      end
    elsif session['sortfil']
      sort_not_change = true
      if session['sortfil'] == 'title'
        @movies = @movies.order(:title)
      else
        @movies = @movies.order(:release_date)
      end
    end
    
    if sort_not_change
      if ratings_not_change
        flash.keep
        redirect_to movies_path(:sort => session['sortfil'], :ratings => session['ratfil'])
      else
        flash.keep
        redirect_to movies_path(:sort => session['sortfil'], :ratings => params[:ratings])
      end
    else
      if ratings_not_change
        flash.keep
        redirect_to movies_path(:sort => params[:sort],:ratings => session['ratfil'])
      end
    end
  end

  def new
    # default: render 'new' template
    reset_session
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def director
    temp = Movie.find_by_id(params[:id])
    if temp.director == ""
      flash[:notice] = "'#{temp.title}' has no director info"
      flash.keep
      redirect_to movies_path
    else
      @movies = Movie.find_all_by_director(temp.director)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/director.html.haml
%h1 Movies With Director

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
      %th Director
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
        %td= movie.director

= link_to 'Back to Movie Details', movie_path(Movie.find_by_id(params[:id]))

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do
  -puts @movie.id
  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
= form_tag movies_path, :id => "ratings_form", :method => :get do
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]",1,@existing.include?(rating)

    / = check_box_tag "ratings[#{rating}]", session[:checkbox][rating], , :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => "ratings_submit"

%h1 All Movies

%table#movies
  %thead
    %tr
      %th{:class => ("hilite" if params[:sort] == "title")}= link_to 'Movie Title', movies_path(:sort => 'title'), :id => "title_header"
      %th Rating
      %th{:class => ("hilite" if params[:sort] == "date")}= link_to 'Release Date', movies_path(:sort => 'date'), :id => "release_date_header"
      %th More Info
      %th Director
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
        %td= movie.director

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path
= link_to 'Find Movies With Same Director', director_path(id: @movie.id)